# https://cibuildwheel.readthedocs.io/en/latest/setup/#appveyor
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      APPVEYOR_JOB_NAME: "python37-x64-vs2015"
      CIBW_BEFORE_ALL: msbuild wasmpy.sln /property:Configuration=Release
      CIBW_BUILD: cp36-*
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
      CIBW_BEFORE_ALL: make
      CIBW_BUILD: cp36-*

stack: python 3.7

init:
- cmd: set PATH=C:\msys64\mingw64\bin;%PATH%
- cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install: python -m pip install cibuildwheel==2.13.1 && python setup.py assemble

build_script: python -m cibuildwheel --output-dir dist

artifacts:
  - path: "dist\\*"
    name: Wheels
