environment:
  PYPI_TOKEN:
    secure: Ej5+0zxoEbzldGFB9gEbEOI81xpoxi+qk2FG5O2JKnw+9seQfRf9iudWM/98pLE2/vi/KkvrGOidtbz3cS3w/ZmtfZiQf/Tp5sG8YlL21oDdRMMW/EZIc049XvAOTsnb2fAziS19I/UNPFpu/Dzo1Xo/KNax5WuX66zWZFJ2P0oFw0Wv36D9aHpfm4IYEHGewVGZMpvXk993HOOZdeZt0uG02zU85EG08EGP092zDp6SL3WsyVZ7YtJn3Lk3W+7c6BKoKG8sKYn61MLi9J9kEQ==
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      BUILD_TYPE: sdist
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      BUILD_TYPE: wheel
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      BUILD_TYPE: wheel

stack: python 3.7

for:
  - matrix:
      only:
        - BUILD_TYPE: sdist

    install: python -m pip install build && make -f linux.mk
    build_script: python -m build --sdist

  - matrix:
      only:
        - BUILD_TYPE: wheel
          APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

    install: python -m pip install build cibuildwheel && make -f linux.mk
    build_script: python -m cibuildwheel --output-dir dist

  - matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    install: python -m pip install build cibuildwheel && C:\MinGW\bin\mingw32-make -f windows.mk
    build_script: python -m cibuildwheel --output-dir dist

artifacts:
  - path: "dist\\*"

deploy:
  description: ""
  provider: GitHub
  auth_token:
    secure: atWS2pKyihyRyTzMopS3FzlG+VT/r3fx5pk+7E2BwvyxdAGiSmH/pDXPBIPArdW0
  artifact: /.*\.(whl|tar\.gz)/
  draft: true
  on:
    branch: main
    APPVEYOR_REPO_TAG: true

after_deploy:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq 'true')
      {
        python -m pip install twine
        python -m twine upload -u __token__ -p ${env:PYPI_TOKEN} --skip-existing dist/*
      }
