environment:
  BUILD_SCRIPT: python -m cibuildwheel --output-dir dist
  PYPI_TOKEN:
    secure: Ej5+0zxoEbzldGFB9gEbEOI81xpoxi+qk2FG5O2JKnw+9seQfRf9iudWM/98pLE2/vi/KkvrGOidtbz3cS3w/ZmtfZiQf/Tp5sG8YlL21oDdRMMW/EZIc049XvAOTsnb2fAziS19I/UNPFpu/Dzo1Xo/KNax5WuX66zWZFJ2P0oFw0Wv36D9aHpfm4IYEHGewVGZMpvXk993HOOZdeZt0uG02zU85EG08EGP092zDp6SL3WsyVZ7YtJn3Lk3W+7c6BKoKG8sKYn61MLi9J9kEQ==
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      BUILD_SCRIPT: python -m build --sdist
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu

stack: python 3.7

init:
  - cmd: set PATH=C:\Python37;C:\Python37\Scripts;C:\msys64\mingw64\bin;%PATH%

install: python -m pip install build cibuildwheel && python setup.py assemble -q --targets=x86,x86_64

build_script:
  - ps: Invoke-Expression $env:BUILD_SCRIPT

artifacts:
  - path: "dist\\*"

deploy:
  - provider: GitHub
    description: ""
    auth_token:
      secure: atWS2pKyihyRyTzMopS3FzlG+VT/r3fx5pk+7E2BwvyxdAGiSmH/pDXPBIPArdW0
    artifact: /.*\.(whl|tar\.gz)/
    draft: true
    on:
      branch: main
      APPVEYOR_REPO_TAG: true

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq 'true')
      {
        python -m pip install twine
        python -m twine upload -u __token__ -p ${env:PYPI_TOKEN} --skip-existing dist/*
      }
