environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      BUILD_SCRIPT: python setup.py sdist
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      BUILD_SCRIPT: python -m cibuildwheel --output-dir dist
      CIBW_BUILD: cp36-*
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      BUILD_SCRIPT: python -m cibuildwheel --output-dir dist
      CIBW_BUILD: cp36-*

stack: python 3.7

init:
  - cmd: set PATH=C:\msys64\mingw64\bin;%PATH%
  - cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install: python -m pip install cibuildwheel==2.13.1 && python setup.py assemble

build_script:
  - ps: $BUILD_SCRIPT
  - sh: $BUILD_SCRIPT

artifacts:
  - path: "dist\\*"
